# General Snakemake config using Singularity
jobs: 200
latency-wait: 30
rerun-triggers:
  - mtime
rerun-incomplete: true
use-singularity: true
use-conda: false
printshellcmds: true
restart-times: 5
local-cores: 1
max-jobs-per-second: 10
max-status-checks-per-second: 10

# Executor configuration for Snakemake 9+
executor: slurm
#slurm-keep-successful-logs: true
slurm-logdir: logs/slurm

# Default resources
default-resources:
  - slurm_partition=cpuq
  #- slurm_account=...
  #see options at https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html

