# General Snakemake config
jobs: 200
latency-wait: 30
rerun-triggers:
  - mtime
rerun-incomplete: true
use-singularity: true
printshellcmds: true
restart-times: 5

# Executor configuration for Snakemake 9+
executor: slurm

# Default resources
default-resources:
  - slurm_partition=cpuq
  #- slurm_account=...
  #see options at https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html
